name: Update Video Stats
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # run once every day at 8:00 UTC
jobs:
  get-new-videos:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
      - name: Update video stats
        continue-on-error: true
        env:
          GRAFANA_CLOUD_ID: ${{secrets.GRAFANA_CLOUD_ID}}
          GRAFANA_API_KEY: ${{secrets.GRAFANA_API_KEY}}
          INFLUX_METRICS_URL: ${{secrets.INFLUX_METRICS_URL}}
        run: npx playwright test update-video-stats.spec.js
      - name: Add and commit changes to videos.json
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add videos.json
          git add users.json
          git commit -m "Update video data"
          git push
